server:
  port: 8084
spring:
  rabbitmq:
    host: 192.168.37.130 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: cx # 虚拟主机
    username: itheima # 用户名
    password: 123321 # 密码
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
hm:
  db:
    database: hm-trade
  swagger:
    title: 交易服务接口文档
    package: com.item.tradeservice.controller
    description: 交易服务接口文档
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123

feign:
  okhttp:
    enabled: true # 开启OKHttp功能
