server:
  port: 8086
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
spring:
    rabbitmq:
      host: 192.168.37.*** # 你的虚拟机IP
      port: 5672 # 端口
      virtual-host: cx # 虚拟主机
      username: itheima # 用户名
      password: 123321 # 密码
hm:
  db:
    database: hm-item
  swagger:
    title: 搜索服务接口文档
    description: 搜索服务相关接口
    package: com.hmall.searchservice.Controller
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
#spring:
#  cloud:
#    sentinel:
#      transport:
#        dashboard: localhost:8090
#        http-method-specify: true # 开启请求方式前缀